name: Reusable Workflow to Deploy .Net App

on: 
  workflow_call:
    inputs:
      package-name: 
        required: true
        type: string
      app-name:
        required: true
        type: string
      deployment-slot:
        required: true
        type: string
    secrets:
      azure-profile:
        required: false
jobs:

  deploy_job:
    runs-on: windows-latest
    
  
    steps:

      - name: Download artificat from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.package-name }}
          
      - name: Secret Information 
        run: echo "Value of secret matches - ${{ secrets.azure-profile == 'placeholder' }}"

      - name: Print name of app service to deploy to
        run: echo "App will be deployed to ${{ inputs.app-name }}"

      - name: List files in root directory
        run: |
          Get-ChildItem -Path . | ForEach-Object { Write-Output $_.Name }
        shell: pwsh
